version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jvnet.staxex:stax-ex
    versions:
    - 2.0.0
  - dependency-name: com.sun.istack:istack-commons-tools
    versions:
    - 4.0.0
  - dependency-name: com.sun.istack:istack-commons-runtime
    versions:
    - 4.0.0
